In [6]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [3]:
glaucoma_dataset = pd.read_csv('GlaucomaM.csv')

In [4]:
glaucoma_dataset

,ag,at,as,an,ai,eag,eat,eas,ean,eai,...,tmt,tms,tmn,tmi,mr,rnf,mdic,emd,mv,Class
0,2.220,0.354,0.580,0.686,0.601,1.267,0.336,0.346,0.255,0.331,...,-0.018,-0.230,-0.510,-0.158,0.841,0.410,0.137,0.239,0.035,normal
1,2.681,0.475,0.672,0.868,0.667,2.053,0.440,0.520,0.639,0.454,...,-0.014,-0.165,-0.317,-0.192,0.924,0.256,0.252,0.329,0.022,normal
2,1.979,0.343,0.508,0.624,0.504,1.200,0.299,0.396,0.259,0.246,...,-0.097,-0.235,-0.337,-0.020,0.795,0.378,0.152,0.250,0.029,normal
3,1.747,0.269,0.476,0.525,0.476,0.612,0.147,0.017,0.044,0.405,...,-0.035,-0.449,-0.217,-0.091,0.746,0.200,0.027,0.078,0.023,normal
4,2.990,0.599,0.686,1.039,0.667,2.513,0.543,0.607,0.871,0.492,...,-0.105,0.084,-0.012,-0.054,0.977,0.193,0.297,0.354,0.034,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,2.801,0.481,0.729,0.888,0.704,1.841,0.312,0.550,0.583,0.396,...,-0.180,-0.224,-0.085,-0.006,0.945,0.121,0.182,0.276,0.033,glaucoma
192,1.698,0.265,0.449,0.530,0.454,1.128,0.211,0.281,0.286,0.351,...,-0.137,-0.209,-0.289,0.043,0.736,0.273,0.207,0.312,0.036,glaucoma
193,2.124,0.402,0.514,0.697,0.511,1.595,0.369,0.430,0.323,0.473,...,-0.071,-0.048,-0.278,0.048,0.823,0.088,0.174,0.231,0.028,glaucoma
194,2.039,0.374,0.491,0.675,0.500,1.561,0.362,0.397,0.316,0.485,...,0.187,0.026,-0.126,0.167,0.808,0.010,0.272,0.355,0.023,glaucoma
195,2.399,0.433,0.575,0.794,0.597,1.292,0.245,0.484,0.186,0.378,...,-0.122,0.134,-0.277,-0.156,0.875,0.075,0.066,0.122,0.016,glaucoma

In [35]:
features = list(glaucoma_dataset.columns)[:-1]

In [36]:
glaucoma_dataset[features]

,ag,at,as,an,ai,eag,eat,eas,ean,eai,...,tmg,tmt,tms,tmn,tmi,mr,rnf,mdic,emd,mv
0,2.220,0.354,0.580,0.686,0.601,1.267,0.336,0.346,0.255,0.331,...,-0.236,-0.018,-0.230,-0.510,-0.158,0.841,0.410,0.137,0.239,0.035
1,2.681,0.475,0.672,0.868,0.667,2.053,0.440,0.520,0.639,0.454,...,-0.211,-0.014,-0.165,-0.317,-0.192,0.924,0.256,0.252,0.329,0.022
2,1.979,0.343,0.508,0.624,0.504,1.200,0.299,0.396,0.259,0.246,...,-0.185,-0.097,-0.235,-0.337,-0.020,0.795,0.378,0.152,0.250,0.029
3,1.747,0.269,0.476,0.525,0.476,0.612,0.147,0.017,0.044,0.405,...,-0.148,-0.035,-0.449,-0.217,-0.091,0.746,0.200,0.027,0.078,0.023
4,2.990,0.599,0.686,1.039,0.667,2.513,0.543,0.607,0.871,0.492,...,-0.052,-0.105,0.084,-0.012,-0.054,0.977,0.193,0.297,0.354,0.034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,2.801,0.481,0.729,0.888,0.704,1.841,0.312,0.550,0.583,0.396,...,-0.144,-0.180,-0.224,-0.085,-0.006,0.945,0.121,0.182,0.276,0.033
192,1.698,0.265,0.449,0.530,0.454,1.128,0.211,0.281,0.286,0.351,...,-0.156,-0.137,-0.209,-0.289,0.043,0.736,0.273,0.207,0.312,0.036
193,2.124,0.402,0.514,0.697,0.511,1.595,0.369,0.430,0.323,0.473,...,-0.102,-0.071,-0.048,-0.278,0.048,0.823,0.088,0.174,0.231,0.028
194,2.039,0.374,0.491,0.675,0.500,1.561,0.362,0.397,0.316,0.485,...,0.027,0.187,0.026,-0.126,0.167,0.808,0.010,0.272,0.355,0.023
195,2.399,0.433,0.575,0.794,0.597,1.292,0.245,0.484,0.186,0.378,...,-0.077,-0.122,0.134,-0.277,-0.156,0.875,0.075,0.066,0.122,0.016

In [37]:
glaucoma_dataset[['Class']]

        Class
0      normal
1      normal
2      normal
3      normal
4      normal
..        ...
191  glaucoma
192  glaucoma
193  glaucoma
194  glaucoma
195  glaucoma

[196 rows x 1 columns]

In [38]:
X_train, X_test, y_train, y_test = train_test_split(glaucoma_dataset[features], glaucoma_dataset[['Class']], random_state=0)

In [39]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (147, 62)
y_train shape: (147, 1)

In [40]:
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_test shape: (49, 62)
y_test shape: (49, 1)

In [42]:
glaucoma_dataset[features].describe()

,ag,at,as,an,ai,eag,eat,eas,ean,eai,...,tmg,tmt,tms,tmn,tmi,mr,rnf,mdic,emd,mv
count,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,...,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000
mean,2.606531,0.458980,0.651781,0.835929,0.659995,1.874138,0.406372,0.486403,0.501214,0.480097,...,-0.092985,-0.004658,-0.039806,-0.147204,-0.036510,0.904985,0.182383,0.231270,0.308903,0.033541
std,0.659789,0.127013,0.158462,0.222166,0.161065,0.721218,0.125941,0.184486,0.286181,0.173977,...,0.108226,0.128062,0.150077,0.134205,0.136423,0.112356,0.094080,0.123882,0.128246,0.021850
min,1.312000,0.201000,0.345000,0.397000,0.369000,0.415000,0.137000,0.017000,0.008000,0.098000,...,-0.353000,-0.291000,-0.449000,-0.510000,-0.405000,0.647000,-0.297000,0.012000,0.047000,0.000000
25%,2.139250,0.370750,0.538500,0.681000,0.550500,1.309250,0.315750,0.380750,0.280500,0.372500,...,-0.161500,-0.101000,-0.135250,-0.231000,-0.127500,0.826000,0.119750,0.144000,0.230500,0.021000
50%,2.533000,0.444500,0.630500,0.808500,0.632000,1.843500,0.402500,0.468500,0.503500,0.484000,...,-0.081000,-0.018500,-0.031500,-0.146500,-0.036000,0.899500,0.182000,0.227000,0.298000,0.028000
75%,2.943500,0.528000,0.738250,0.952000,0.749750,2.317000,0.483250,0.605500,0.689500,0.594750,...,-0.025250,0.087750,0.068000,-0.056250,0.049500,0.968500,0.237000,0.299250,0.379250,0.038250
max,5.444000,0.967000,1.340000,1.765000,1.373000,4.125000,0.848000,1.225000,1.568000,0.961000,...,0.192000,0.366000,0.358000,0.245000,0.418000,1.317000,0.451000,0.663000,0.743000,0.183000

In [73]:
knn = KNeighborsClassifier(n_neighbors=10)

In [74]:
np.array(y_train).reshape(147)

array(['normal', 'glaucoma', 'normal', 'normal', 'glaucoma', 'normal',
       'glaucoma', 'glaucoma', 'normal', 'normal', 'glaucoma', 'glaucoma',
       'normal', 'glaucoma', 'normal', 'normal', 'glaucoma', 'glaucoma',
       'glaucoma', 'normal', 'normal', 'glaucoma', 'glaucoma', 'glaucoma',
       'normal', 'normal', 'normal', 'glaucoma', 'normal', 'glaucoma',
       'glaucoma', 'normal', 'normal', 'normal', 'glaucoma', 'glaucoma',
       'normal', 'normal', 'glaucoma', 'normal', 'glaucoma', 'glaucoma',
       'glaucoma', 'glaucoma', 'normal', 'glaucoma', 'glaucoma',
       'glaucoma', 'normal', 'normal', 'normal', 'glaucoma', 'normal',
       'normal', 'glaucoma', 'normal', 'normal', 'normal', 'normal',
       'normal', 'normal', 'glaucoma', 'normal', 'glaucoma', 'glaucoma',
       'normal', 'normal', 'normal', 'glaucoma', 'normal', 'glaucoma',
       'normal', 'normal', 'glaucoma', 'glaucoma', 'glaucoma', 'normal',
       'normal', 'normal', 'normal', 'glaucoma', 'glaucoma', 'glaucoma',
       'glaucoma', 'normal', 'glaucoma', 'normal', 'glaucoma', 'glaucoma',
       'normal', 'normal', 'normal', 'normal', 'glaucoma', 'glaucoma',
       'normal', 'glaucoma', 'glaucoma', 'glaucoma', 'normal', 'normal',
       'glaucoma', 'normal', 'glaucoma', 'glaucoma', 'normal', 'normal',
       'glaucoma', 'glaucoma', 'normal', 'glaucoma', 'glaucoma',
       'glaucoma', 'normal', 'glaucoma', 'glaucoma', 'glaucoma', 'normal',
       'glaucoma', 'normal', 'normal', 'glaucoma', 'glaucoma', 'glaucoma',
       'normal', 'normal', 'normal', 'glaucoma', 'normal', 'glaucoma',
       'glaucoma', 'glaucoma', 'normal', 'normal', 'glaucoma', 'normal',
       'normal', 'normal', 'normal', 'normal', 'normal', 'glaucoma',
       'normal', 'glaucoma', 'glaucoma', 'normal', 'glaucoma'],
      dtype=object)

In [75]:
np.array(X_train)

array([[3.909, 0.652, 1.008, ..., 0.464, 0.587, 0.019],
       [2.524, 0.474, 0.596, ..., 0.341, 0.376, 0.125],
       [1.893, 0.327, 0.488, ..., 0.121, 0.203, 0.035],
       ...,
       [1.749, 0.264, 0.482, ..., 0.156, 0.251, 0.047],
       [2.173, 0.336, 0.604, ..., 0.047, 0.102, 0.061],
       [3.222, 0.567, 0.8  , ..., 0.292, 0.376, 0.03 ]])

In [76]:
knn.fit(X_train, np.array(y_train).reshape(147))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [77]:
y_pred = knn.predict(X_test)
print("Test set predictions: {}".format(y_pred))
print("Test set accuracy: {:.2f}%".format(np.mean(y_pred==np.array(y_test).reshape(49))*100))

Test set predictions: ['normal' 'glaucoma' 'normal' 'glaucoma' 'normal' 'glaucoma' 'normal'
 'normal' 'normal' 'normal' 'normal' 'normal' 'glaucoma' 'glaucoma'
 'glaucoma' 'glaucoma' 'glaucoma' 'normal' 'normal' 'glaucoma' 'normal'
 'glaucoma' 'glaucoma' 'glaucoma' 'normal' 'normal' 'glaucoma' 'glaucoma'
 'glaucoma' 'normal' 'normal' 'glaucoma' 'normal' 'normal' 'glaucoma'
 'glaucoma' 'normal' 'normal' 'glaucoma' 'glaucoma' 'glaucoma' 'glaucoma'
 'glaucoma' 'normal' 'normal' 'glaucoma' 'glaucoma' 'glaucoma' 'glaucoma']
Test set accuracy: 77.55%